import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import MianFooter from "@/components/MainFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "figma project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-950 text-white w-screen">
        <header>
          <NavBar />
        </header>
        {children}
        <footer>
          <MianFooter />
        </footer>
      </body>
    </html>
  );
}
